# Generated by Django 3.0.7 on 2022-06-27 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teams',
            old_name='google_line',
            new_name='google_link',
        ),
    ]
